name: UPDATE

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Set python environment
env:
  PYTHON_VERSION: 3.9.1

# Job Descriptions
jobs:
  stock_update:
    name: Stock Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      
      - name: Package Setup
        run: make setup
      - name: Run Lint
        run: make lint
  
      - name: print directory
        run: pwd
      - name: Run Scrape
        run: make run
